import { Component, OnInit, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AttendanceAdminService } from '@core/services/attendance-admin.service';
import { UserService } from '@core/services/user.service';
import { ToastService } from '@core/services/toast.service';
import { AttendanceGroup, AttendanceQueue, QueueMember, User } from '@shared/models';

@Component({ selector: 'app-attendance-queues-page', standalone: true, imports: [CommonModule, ReactiveFormsModule], template: `
<div class="p-6 space-y-6"><div><h1 class="text-2xl font-bold">Filas de Atendimento</h1><p class="text-sm text-slate-500">Configure distribuição e os operadores que podem receber novas conversas.</p></div>
<div class="grid lg:grid-cols-3 gap-6"><section class="lg:col-span-2 space-y-4"><form [formGroup]="form" (ngSubmit)="save()" class="grid md:grid-cols-2 gap-3 p-4 rounded-xl border bg-white dark:bg-slate-900"><input formControlName="name" placeholder="Nome da fila" class="input"/><select formControlName="groupId" class="input"><option [ngValue]="null">Selecione o grupo</option>@for (group of groups();track group.id){<option [ngValue]="group.id">{{group.name}}</option>}</select><select formControlName="distributionPolicy" class="input">@for(policy of policies;track policy){<option [value]="policy">{{policy}}</option>}</select><label class="flex items-center gap-2 text-sm"><input type="checkbox" formControlName="active"/> Ativa</label><button class="btn-primary md:col-span-2" [disabled]="form.invalid">{{editing()?'Salvar fila':'Criar fila'}}</button></form>
<div class="rounded-xl border overflow-hidden"><table class="w-full text-sm"><thead><tr><th>Fila</th><th>Grupo</th><th>Política</th><th></th></tr></thead><tbody>@for(queue of queues();track queue.id){<tr><td><b>{{queue.name}}</b><div class="text-slate-500">{{queue.active?'Ativa':'Inativa'}}</div></td><td>{{queue.groupName}}</td><td>{{queue.distributionPolicy}}</td><td><button class="link" (click)="edit(queue)">Editar</button> <button class="link" (click)="select(queue)">Operadores</button></td></tr>}</tbody></table></div></section>
<section class="rounded-xl border p-4 space-y-3 bg-white dark:bg-slate-900"><h2 class="font-semibold">{{selected()?.name||'Operadores da fila'}}</h2>@if(selected()){<form [formGroup]="memberForm" (ngSubmit)="saveMember()" class="space-y-2"><select formControlName="userId" class="input"><option [ngValue]="null">Selecione o usuário</option>@for(user of users();track user.id){<option [ngValue]="user.id">{{user.name}}</option>}</select><input class="input" type="number" min="1" formControlName="maxSimultaneousAttendances" placeholder="Capacidade"/><select formControlName="status" class="input"><option value="AVAILABLE">Disponível</option><option value="BUSY">Ocupado</option><option value="OFFLINE">Offline</option></select><button class="btn-primary w-full" [disabled]="memberForm.invalid">Adicionar / atualizar</button></form><div class="divide-y">@for(member of members();track member.id){<div class="py-2 flex justify-between"><span>{{member.userName}} <small class="text-slate-500">{{member.currentActiveAttendances}}/{{member.maxSimultaneousAttendances}} · {{member.status}}</small></span><button class="link text-red-600" (click)="removeMember(member)">Remover</button></div>}</div>}@else{<p class="text-sm text-slate-500">Selecione uma fila para administrar operadores.</p>}</section></div></div>`,styles:[`.input{width:100%;padding:.55rem .7rem;border:1px solid #cbd5e1;border-radius:.5rem;background:transparent}.btn-primary{padding:.55rem .8rem;border-radius:.5rem;background:#2563eb;color:white}.link{color:#2563eb;font-size:.8rem}th,td{padding:.75rem;text-align:left;border-bottom:1px solid #e2e8f0}`]})
export class AttendanceQueuesPageComponent implements OnInit {
 private api=inject(AttendanceAdminService);private usersApi=inject(UserService);private toast=inject(ToastService);private fb=inject(FormBuilder); policies=['ROUND_ROBIN','LEAST_BUSY','PRIORITY','MANUAL','RANDOM'] as const;
 groups=signal<AttendanceGroup[]>([]);queues=signal<AttendanceQueue[]>([]);users=signal<User[]>([]);members=signal<QueueMember[]>([]);selected=signal<AttendanceQueue|null>(null);editing=signal<AttendanceQueue|null>(null);
 form=this.fb.group({name:['',Validators.required],groupId:[null as number|null,Validators.required],distributionPolicy:['ROUND_ROBIN' as typeof this.policies[number],Validators.required],active:[true]});memberForm=this.fb.group({userId:[null as number|null,Validators.required],maxSimultaneousAttendances:[5,[Validators.required,Validators.min(1)]],status:['AVAILABLE' as 'AVAILABLE'|'BUSY'|'OFFLINE',Validators.required]});
 ngOnInit(){this.load();this.api.groups().subscribe({next:x=>this.groups.set(x.filter(g=>g.active))});this.usersApi.getAll().subscribe({next:x=>this.users.set(x)});}
 load(){this.api.queues().subscribe({next:x=>this.queues.set(x),error:()=>this.toast.error('Erro ao carregar filas')});}
 edit(q:AttendanceQueue){this.editing.set(q);this.form.reset({name:q.name,groupId:q.groupId,distributionPolicy:q.distributionPolicy,active:q.active});}
 save(){if(this.form.invalid)return;const v=this.form.getRawValue();const req={name:v.name!,groupId:v.groupId!,distributionPolicy:v.distributionPolicy!,active:v.active??true};const current=this.editing();const call=current?this.api.updateQueue(current.id,req):this.api.createQueue(req);call.subscribe({next:()=>{this.toast.success('Fila salva');this.form.reset({name:'',groupId:null,distributionPolicy:'ROUND_ROBIN',active:true});this.editing.set(null);this.load();},error:e=>this.toast.error(e.error?.message||'Não foi possível salvar a fila')});}
 select(q:AttendanceQueue){this.selected.set(q);this.loadMembers();} loadMembers(){const q=this.selected();if(q)this.api.queueMembers(q.id).subscribe({next:x=>this.members.set(x),error:()=>this.toast.error('Erro ao carregar operadores')});}
 saveMember(){const q=this.selected(),v=this.memberForm.getRawValue();if(!q||!v.userId)return;this.api.upsertQueueMember(q.id,{userId:v.userId,maxSimultaneousAttendances:v.maxSimultaneousAttendances!,status:v.status!}).subscribe({next:()=>{this.memberForm.reset({userId:null,maxSimultaneousAttendances:5,status:'AVAILABLE'});this.loadMembers();},error:e=>this.toast.error(e.error?.message||'Erro ao salvar operador')});}
 removeMember(m:QueueMember){const q=this.selected();if(q)this.api.removeQueueMember(q.id,m.id).subscribe({next:()=>this.loadMembers(),error:()=>this.toast.error('Erro ao remover operador')});}
}
